In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OrdinalEncoder

In [2]:
data=[["Good","x"],["VG","y"],["Ex",'z']]

In [3]:
o=OrdinalEncoder()

In [4]:
o.fit_transform(data)

array([[1., 0.],
       [2., 1.],
       [0., 2.]])

In [5]:
data

[['Good', 'x'], ['VG', 'y'], ['Ex', 'z']]

In [11]:
q=OrdinalEncoder(categories=[["Good","VG","Ex"],["x","y",'z']])

In [12]:
q.fit_transform(data)

array([[0., 0.],
       [1., 1.],
       [2., 2.]])

In [17]:
data1=[["Good"],["VG"],["Ex"]]

In [18]:
q=OrdinalEncoder(categories=[["Good","VG","Ex"]])

In [19]:
q.fit_transform(data1)

array([[0.],
       [1.],
       [2.]])